import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getTranslations } from "next-intl/server";
import "./globals.css";
import ClientLayout from "./clientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const t = await getTranslations();

  return (
    <html lang="en">
      <body
        dir={t("direction")}
        className={`antialiased`}
      >
        <main className="bg-gray-100 min-h-screen">
          <NextIntlClientProvider>
            <ClientLayout>
              {children}
            </ClientLayout>
          </NextIntlClientProvider>
        </main>
      </body>
    </html>
  );
}
